### ISSUE TITLE
Sort issues by given tags

### ISSUE THREAD

**Issue by mattab** [piwik/github-changelog-generator#1]
As a release manager I would like the issues to be sorted in order of their importance automatically. For Piwik it means that the following order can be applied:
1. issues tagged with `Major`
2. issues `Enhancement`
3. issues `Task`
4. issues `Bug`

This will save me some time to re-order the issues by how I perceive them to be important. it's quite difficult when 70+ issues in the changelog.

**Comment by tsteur** [comment]
_should_ work

**Comment by mattab** [comment]
awesome! will save me 30 minutes+ per month :-)
