### ISSUE TITLE
Pull Requests appear in the same changelog entry as the parent issue

### ISSUE THREAD

**Issue by mattab** [piwik/github-changelog-generator#2]
The goal of this issue is to improve the changelog generator to prevent the same issue / feature / bug from taking two lines in the changelog. This occurs because often we create an issue for a bug or feature and then the issue is closed with a pull request. 

For example we have today:

```
#6687 Fix for IE9 in compatibility mode [by @Fensterbank, @mnapoli]
#6163 Overriding Compatibility View in IE9 [by @Fensterbank]
```

instead maybe we could have this:

```
#6163 Overriding Compatibility View in IE9 via Pull Request #6687 [by @Fensterbank, @mnapoli]
```

or maybe:

```
#6163 Overriding Compatibility View in IE9 via PR  #6687 'Fix for IE9 in compatibility mode' [by @Fensterbank, @mnapoli]
```

**Comment by mattab** [comment]
Here is an idea:
- if a PR is merged, if the PR description contains "fixes #xyz" and if #xyz has been closed, then we can assume that this PR was fixing #xyz and therefore we can hide it from the changelog.

**Comment by mattab** [comment]
Or maybe another solution would be to ask every developer in Piwik project that, when merging a pull request, if the PR already has an issue, to add the label `not-in-changelog`. Maybe that's best solution rather than try to automate it?

**Comment by mnapoli** [comment]
I think it makes sense to use the label.

**Comment by mattab** [comment]
at Piwik we are using the `not-in-changelog` label which is the best solution for us. Automating it as suggested here was not possible. All good :+1:
